name: build-test

on:
  pull_request_target:
    types: [opened, synchronize, reopened, labeled]

jobs:
  build-kots:
    runs-on: ubuntu-18.04
    # only run this workflow if:
    #   not a fork or user is dependabot or PR is labeled with '@actions/safe-to-test'
    if: >
      github.event.pull_request.head.repo.full_name == github.repository ||
      github.event.pull_request.user.login == 'dependabot[bot]' || 
      contains(github.event.pull_request.labels.*.name, '@actions/safe-to-test')
    steps:
      - uses: actions/setup-go@v2.1.3
        with:
          go-version: "1.14.3"

      - name: setup env
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
        shell: bash

      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world, running jalaja test!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Printing github actors and event names
          echo User login
          echo ${{github.event.pull_request.user.login}}
          echo github actor
          echo ${{github.actor}}
          echo github event name
          echo ${{github.event_name}}

      - uses: actions/dotenv-action@v0.2.7
        id: dotenv
        with: 
          path: .image.env 

      - name: using dotenv action
        shell: bash
        run: |
          echo ${{ steps.dotenv.outputs.minio_tag }}

