name: build-test

on:
  pull_request_target:
    types: [opened, synchronize, reopened, labeled]

jobs:
  build-kots:
    runs-on: ubuntu-18.04
    if: contains(github.event.pull_request.labels.*.name, '@actions/safe-to-test')
    steps:
      - uses: actions/setup-go@v2.1.3
        with:
          go-version: "1.14.3"

      - name: setup env
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
        shell: bash

      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world, running jalaja test!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build todo ,
          echo test, and deploy your project todo .


       

